services:
  it.inputmask.form.type.date_mask:
    class: IT\InputMaskBundle\Form\Type\DateMaskType
    tags:
      - { name: 'form.type', alias: 'it_date_mask' }

  it.inputmask.form.type.text_mask:
    class: IT\InputMaskBundle\Form\Type\TextMaskType
    tags:
      - { name: 'form.type', alias: 'it_text_mask' }